# Generated by Django 5.1.3 on 2025-03-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('Card', 'Credit Card'), ('cod', 'Cash on Delivery')], default='PayPal', max_length=10),
        ),
    ]
