# Generated by Django 5.1.7 on 2025-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Laptop', 'Laptop'), ('Phone', 'Phone'), ('Camera', 'Camera'), ('Watch', 'Watch'), ('Tablet', 'Tablet')], default='Phone', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='count_in_stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
